trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*
pr:
  branches:
    include:
      - main

variables:
  - group: sonarqube
  - group: sign
  - group: ossrh
  - name: dockerRegistryServiceConnection
    value: docker_hub

resources:
  repositories:
    - repository: templates
      type: github
      name: bakdata/bakdata-project-templates
      endpoint: bot

jobs:
  - template: azure/gradle/build.yml@templates
    parameters:
      docker: 'true'
  - template: azure/gradle/create_tag_version.yml@templates
  - template: azure/gradle/upload_release.yml@templates
    parameters:
      docker: 'true'
  - template: azure/gradle/upload_snapshot.yml@templates
    parameters:
      docker: 'true'
