apiVersion: v1
name: kafka-connect-resetter
description: A helm chart for deploying a Kafka Connect resetter.
version: 0.1.0
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
