apiVersion: v1
entries:
  kafka-connect-resetter:
    - apiVersion: v1
      created: "2022-09-30T11:45:25.4764906+02:00"
      description: A helm chart for deploying a Kafka Connect resetter.
      digest: b9960c63c0ee3a28e09fd1a1cbe855c7af720c7842651023e1406d9ea1d0a1c7
      name: kafka-connect-resetter
      urls:
        - kafka-connect-resetter/kafka-connect-resetter-0.1.0.tgz
      version: 0.1.0
generated: "2022-09-30T11:45:25.4693368+02:00"
