{{- $root := . -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cleanup-job.fullname" . }}
{{- if .Values.annotations }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "cleanup-job.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  {{- if .Values.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
      labels:
        {{- include "cleanup-job.labels" . | nindent 8 }}
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          args:
            - {{ .Values.connectorType }}
            - {{ .Values.config.connector }}
            {{- if hasKey .Values.config "brokers" }}
            - "--brokers"
            - {{ .Values.config.brokers }}
            {{- end }}
            {{- if eq .Values.connectorType "sink"}}
            {{- if and (hasKey .Values.config "deleteConsumerGroup") (.Values.config.deleteConsumerGroup) }}
            - "--delete-consumer-group"
            {{- end }}
            {{- end }}
            {{- if eq .Values.connectorType "source"}}
            {{- if and (hasKey .Values.config "offsetTopic") }}
            - "--offset-topic"
            - {{ .Values.config.offsetTopic }}
            {{- end }}
            {{- if hasKey .Values.config "pollDuration" }}
            - "--poll-duration"
            - {{ .Values.config.pollDuration }}
            {{- end }}
            {{- end }}
            {{- if .Values.config.config }}
            - "--config"
            - "{{- range $key, $value := .Values.config.config }}{{ $key }}={{ $value }},{{- end }}"
            {{- end }}
          {{- if .Values.secretRefs }}
          env:
            {{- range $key, $value := .Values.secretRefs }}
            - name: "{{ $key }}"
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: "{{ $value.key }}"
            {{- end }}
          {{- end }}
