name: Helm lint
# Reusable workflow for packaging and publishing Helm charts having multiple subcharts on GitHub pages

on:
  push:

jobs:
  helm-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Lint Helm chart
        uses: bakdata/ci-templates/actions/helm-lint@v1.10.0
        with:
          lint-config-path: ".github/lint-config.yaml"